cat("waRRior: Installing libraries:\n")
waRRior.libraries.checkPkg('devtools')
waRRior.libraries.checkPkg('Hmisc')
waRRior.libraries.checkPkg('MASS')
waRRior.libraries.checkPkg('plyr')
waRRior.libraries.checkPkg('dplyr')
waRRior.libraries.checkPkg('RJSONIO')
waRRior.libraries.checkPkg('RCurl')
waRRior.libraries.checkPkg('googleVis')
waRRior.libraries.checkPkg('shiny')
waRRior.libraries.checkPkg('RSQLite')
waRRior.libraries.checkPkg('sqldf')
waRRior.libraries.checkPkg('zoo')
waRRior.libraries.checkPkg('doParallel')
cat("waRRior: Packages installed.\n)
