waRRior.snippets.verbose("loading startup libraries:\n", verbose_ = T)
require(RCurl)
require(plyr)
require(dplyr)
require(RJSONIO)
waRRior.snippets.verbose("startup libraries loaded.\n", verbose_ = T)
